### PR TITLE
added book icon and hover effect

### PR DESCRIPTION
**Pull request by akriity**
I added a new book icon in the nav bar and hover effect in social media icon  according to the theme color of the site.Have a look here!
Screenshot (906)

### CODE REVIEW

**Comment by ALOKARYAN51** [comment]
why commit in master branch @Aacrity

**Comment by ALOKARYAN51** [comment]
you PR in master branch go to readme section @Aacrity

**Comment by Aacrity** [comment]
i couldnt resolve

**Comment by akriity** [comment]
is it done now?

**Pull request closed without merging**
