### PR TITLE
feat: Added light theme and added functionality to change theme button

### LINKED ISSUE #5: Add light mode.

### PR DESCRIPTION
**Pull request by chetas411**
Created light and dark theme classes using CSS varaibles  and added functionality with javascript  to switch between the two themes through the toggle button.
It Fixes #5 
Library - Mozilla Firefox 2020-10-04 13-17-44-min(1)

### CODE REVIEW

**Comment by chetas411** [comment]
@ALOKARYAN51 Can you review the PR?

**Review by ALOKARYAN51 — APPROVED** [review]

**Comment by ALOKARYAN51** [comment]
please check navbar is not displaying in mobile view @chetas411

**Comment by chetas411** [comment]
> 
> 
> please check navbar is not displaying in mobile view @chetas411

ok let me check

**Comment by chetas411** [comment]
> 
> 
> please check navbar is not displaying in mobile view @chetas411

@ALOKARYAN51 I fixed the navbar issue , you can now merge this Pull request #12  .

Screen Shot 2020-10-04 at 16 09 34
Screen Shot 2020-10-04 at 16 09 42
Screen Shot 2020-10-04 at 16 09 48
Screen Shot 2020-10-04 at 16 09 52

**Comment by chetas411** [comment]
@ALOKARYAN51 waiting for your review ?

**Pull request merged**
